# Generated by Django 3.1.6 on 2021-02-12 18:43

from django.db import migrations, models
import django_msat.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='document',
            field=models.FileField(blank=True, null=True, storage=django_msat.storage_backends.PrivateMediaStorage(), upload_to='private/'),
        ),
    ]
