# Generated by Django 3.1.6 on 2021-02-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20210212_1904'),
        ('assessments', '0002_assessment_document'),
    ]

    operations = [
    ]
