# Generated by Django 3.1.6 on 2021-02-12 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0003_auto_20210212_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order_id',)},
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'ordering': ('order_id',), 'verbose_name_plural': 'Question categories'},
        ),
        migrations.AddField(
            model_name='assessment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.BooleanField(null=True),
        ),
    ]
