# Generated by Django 3.1.6 on 2021-02-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_merge_20210212_1905'),
        ('assessments', '0004_auto_20210212_2055'),
    ]

    operations = [
    ]
