# Generated by Django 3.1.6 on 2021-02-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_auto_20210212_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('category', 'order_id')},
        ),
    ]
